Sigma cleanup
zcoinofficial/zcoin pull request #884
Opened 2020-07-16 07:33 UTC by levonpetrosyan93

#219  Code changes brief
Removed code functions for Sigma transaction generation.

2020-07-16 07:48 UTC, riordant commented
@levonpetrosyan93 perhaps squash both commits for one atomic commit?

2020-07-17 11:35 UTC, thebevrishot commented
@levonpetrosyan93 please fix a conflict

2020-09-02 18:56 UTC, thebevrishot commented on src/test/sigma_state_tests.cpp
> +    std::vector<sigma::PrivateCoin> privCoins(generateCoins(sigmaParams, moreMintsToMakeExceedLimit, testDenomination));
please apply here also

2020-09-02 20:12 UTC, levonpetrosyan93 commented on src/test/sigma_manymintspend_test.cpp
> +            pwalletMain->zwallet->GetTracker().SetPubcoinUsed(primitives::GetPubCoinValueHash(mint.value), uint256());
if we don't roll back it tires to use already used coins

2020-09-02 20:13 UTC, levonpetrosyan93 commented on src/test/sigma_mintspend_test.cpp
> +        pwalletMain->SpendSigma(recipients, wtx);
ok will add

2020-09-02 20:13 UTC, levonpetrosyan93 commented on src/test/sigma_state_tests.cpp
> +        std::vector<sigma::PrivateCoin> privCoins(generateCoins(sigmaParams, mintThisBlock, testDenomination));
ah, ok got you, agree. will change

2020-09-02 20:13 UTC, levonpetrosyan93 commented on src/test/sigma_state_tests.cpp
> +    std::vector<sigma::PrivateCoin> privCoins(generateCoins(sigmaParams, moreMintsToMakeExceedLimit, testDenomination));
ok

2020-09-04 12:44 UTC, psolstice requested changes

2020-09-04 12:44 UTC, psolstice commented on src/wallet/wallet.cpp
> +        throw std::runtime_error(_("Sigma is disabled at this period."));
This checks are not relevant currently, should be removed and padding flag should be always set to true. There are creation and mempool-related checks not covered by this PR which should be removed too (`validation.cpp:3471`, `sigmaspendbuilder.cpp:76`, `rpctx.cpp:1757` and probably others). Only `CheckTransaction` when transaction is mined into the block should care about non-true padding flag

2020-09-05 07:18 UTC, psolstice requested changes
Also look at `sigma.cpp:296`. Mempool case hack should be removed. Should be just
```
nHeight >= params.nSigmaPaddingBlock
```

2020-09-05 07:18 UTC, psolstice commented on src/wallet/wallet.cpp
>   * @param vecSend
This function looks like it could benefit from cleanup too. Lots of commented out code. And probably needs to be renamed

2020-09-07 10:10 UTC, psolstice approved these changes
Zerocoin naming should be removed in subsequent PRs

2020-09-08 05:32 UTC, thebevrishot commented on src/test/sigma_manymintspend_test.cpp
> +            pwalletMain->zwallet->GetTracker().SetPubcoinUsed(primitives::GetPubCoinValueHash(mint.value), uint256());
ah I see

2020-09-09 06:56 UTC, thebevrishot approved these changes
LGTM

2020-09-09 12:19 UTC, thebevrishot commented
@levonpetrosyan93 I have tried to reindex and sync from scratch and they works as expected. It should safe to merge now.

2020-09-09 13:09 UTC, merged